tables:
  photo:
    id: [INTEGER, PRIMARY KEY, AUTOINCREMENT]
    type: [INTEGER]
    name: [TEXT]
    description: [TEXT]
    gallery: [TEXT]
    width: [INTEGER]
    height: [INTEGER]

  geodata:
    id: [INTEGER, PRIMARY KEY, AUTOINCREMENT]
    lat: [REAL]
    lng: [REAL]
    gpx: [TEXT]
  
  gallery:
    id: [INTEGER, PRIMARY KEY, AUTOINCREMENT]
    name: [TEXT]
    path: [TEXT]
    lat: [REAL]
    lon: [REAL]
    splash: [TEXT]
    hasgpx: [INTEGER]
    owner: [INTEGER]
    is_protected: [INTEGER]
    whitelist: [TEXT]
    splashWidth: [INTEGER]
    splashHeight: [INTEGER]

  user:
    id: [INTEGER, PRIMARY KEY, AUTOINCREMENT]
    name: [TEXT]
    passhash: [TEXT]
    admin: [INTEGER]
  
  metadata:
    key: [TEXT, PRIMARY KEY]
    value: [TEXT]
